name: chat_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: null
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  google_sign_in: ^5.0.2
  random_string: ^2.1.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
